### PR TITLE
refactor cat.strategy.js

### PR DESCRIPTION
**Pull request by dl90**
fixed issues from previous branch refactor-cat1

### CODE REVIEW

**Comment by joelnet** [comment]
It looks like there's a couple of bugs in the code.

You can run the code with the command:

```bash
npm run start
```

Then in another terminal window:

```bash
npx the-terminal http://0.0.0.0:18000
```

After that you can test each scenario. You'll have to "play" until you get to the "nscan" section so you can `cat` a file.

**Comment by joelnet** [comment]
I can see in `src/commands/cat/strategies/dirExists.strategy.js`:

```javascript
const test = req => {
  const [command] = getArgs(req.body.line)
  return command === 'dirExist'
}
```

Should be something like:
```javascript
const test = req =>
  dirExists({ dir: path, username, session: req.session })
```

**Comment by dl90** [comment]
i made the changes you suggested and tried to run it with my existing version.
seems like cat command cant be found
Screen Shot 2019-11-02 at 9 04 03 PM

**Comment by joelnet** [comment]
Okay, I see what is happening. Unlike `wallet`, the `cat` command is available by default and doesn't require installing, so you can remove these codes from `cat.command.js`:

```javascript
// remove
const { doesServerHavePackage } = require('../lib/doesServerHavePackage')

// modify to be this:
const test = isCommand(name)
```

Next do this to start debugging locally:

- First, open up VSCODE
- Go to the Debug tab on the left and from the dropdown above, select Launch Program
- Now hit Play (F5)

This will start the debugger

- Open `fileExists.strategy.js`
- Click to the left of a line number to add a breakpoint. For this example, choose line 7.
- `npx the-terminal http://0.0.0.0:18000` to connect to your local instance
- login
- use the `cat` command

Now that the debugger is fired up, I can see this code in `fileExists.stragey.js`:

```javascript
const test = req => {
  const [command] = getArgs(req.body.line)
  // The original code in `cat.command.js` doesn't have this line
  return command === 'fileExist'
}
```

`arg` is actually the first thing typed after `cat`. so if you do `cat ~/servers`, `arg` would be `~/servers`.

I hope this helps a little bit. If you have more questions, let me know!

**Comment by dl90** [comment]
I think Im way over my-head with this one, don't really know what Im doing or how to fix the bugs.
Screen Shot 2019-11-09 at 9 10 10 PM
Screen Shot 2019-11-09 at 9 27 52 PM
Screen Shot 2019-11-09 at 9 10 06 PM

**Comment by joelnet** [comment]
I'll try to help.

Push up the code to this branch so I can run it and see. It's hard to tell just from the screenshots.

**Comment by joelnet** [comment]
Okay, so I was able to take a peek at what you have.

I was looking inside of `fileExists.strategy.js` and this file should return the file when one exists, but it seems like the code you have in there is for when a file does not exist, based on this line:

```javascript
return [actions.echo(`cat: ${arg}: No such file or directory`)]
```

So I would think the file should look something like this:

```javascript
const { getDir } = require('../../../filesystem/getDir')
const { getArgs } = require('../../../lib/command')
const actions = require('../../../actions')
const { tables } = require('../../../stores/fs')

const test = req => {
  const {
    username,
    env: { PWD: pwd }
  } = req.session

  const [arg] = getArgs(req.body.line)
  const path = getDir({ username, pwd, dir: arg })

  return path === `/home/${username}/servers`
}

const exec = req => {
  const { username } = req.session

  const servers = tables.servers.find({
    owner: { $eq: username },
    address: { $ne: 'home' }
  })

  return [actions.echo(servers.map(server => server.address).join('\n'))]
}

module.exports = {
  sort: 10,
  test,
  exec
}
```

Let me know if you have some questions about some of the other strategies.

**Comment by dl90** [comment]
I hard coded "cat" in the invalid.strategy.js because it kept on returning undefined if you try to cat an invalid arg.

**Comment by joelnet** [comment]
> I hard coded "cat" in the invalid.strategy.js because it kept on returning undefined if you try to cat an invalid arg.

This is correct. Had issues with this in another refactor.

**Comment by dl90** [comment]
updated fork with current version

**Comment by joelnet** [comment]
Some unit tests have been created for the `cat` command. Try to import the tests and maybe that will help with some of the use cases. There are a couple of tests that are failing.

Run these commands in your shell:

```bash
git fetch
git rebase origin/master
```

Edit the file `src/commands/__tests__/cat.command.js` and change the following line:

```javascript
// change this:
const { exec } = require('../cat.command')

// to this:
const { exec } = require('../cat/cat.command')
```

**Comment by dl90** [comment]
Hi joelnet 

I'm not sure strategy should I add this line to.
https://github.com/joelnet/the-terminal-daemon/blob/e5827e495a7523d544fc86743b2f1d7b49ef9a91/src/commands/cat.command.js#L54

All the strategies are separated so should I add it to cat.command.js itself?

**Comment by joelnet** [comment]
Good question! That is the default case. So that will be a strategy that is `test = () => true`. You'll set the `sort` on the default case higher than the others, so it will run last.

You could call that strategy something like `notfound.strategy.js`

**Pull request closed without merging**
