### PR TITLE
refactored cat command to follow strategy pattern

### PR DESCRIPTION
**Pull request by Ashirogi-Muto**

### CODE REVIEW

**Comment by joelnet** [comment]
Okay I have had some time to look at this.

First, the test function in `cat.command.js` should be:

```javascript
const test = isCommand(name)
```

The strategy pattern isn't well documented on how to use it. But basically the `doesServerHavePackage` part that is removed is causing the strategies to not run. This is because `cat` isn't a "package". So it always returns `false` for `cat`.

Second, also not documented, is the strategies always return a Promise. So when converting to a strategy, it goes from sync to async. Sorry I forgot about this.

So the tests need to change to this:

```javascript
const { exec } = require('../cat.command')
const { onLoad } = require('../../../stores/fs')

describe('commands/cat', () => {
  const session = {
    env: {
      HOST: 'home',
      user: 'test'
    }
  }

  beforeAll(async () => {
    await new Promise(onLoad)
  })

  test('cat("/bin") should return: is a directory', async () => {
    const directory = '/bin'
    const [actual] = await exec({ session, body: { line: `cat ${directory}` } })
    const expected = {
      type: 'ECHO',
      value: `cat: ${directory}: Is directory`
    }
    expect(actual).toMatchObject(expected)
  })

  test('cat("/x89341/ff8312") should return: No such file or directory', async () => {
    const file = '/x89341/ff8312'
    const [actual] = await exec({ session, body: { line: `cat ${file}` } })
    const expected = {
      type: 'ECHO',
      value: `cat: ${file}: No such file or directory`
    }
    expect(actual).toMatchObject(expected)
  })

  test('cat("/bin/ls") should return: File cannot be output', async () => {
    const file = '/bin/ls'
    const [actual] = await exec({ session, body: { line: `cat ${file}` } })
    const expected = {
      type: 'ECHO',
      value: `cat: ${file}: File cannot be output`
    }
    expect(actual).toMatchObject(expected)
  })
})
```

Once you put this test in, you should see 2 tests failing and 1 passing. But now you'll see the result returned instead of just `undefined`. This should help you debug the code.

This should give you some hints. Hit me up on Discord if you have more questions.

**Comment by Ashirogi-Muto** [comment]
Thanks for the feedback! I'll make the necessary changes.

**Comment by joelnet** [comment]
Okay, I finally had some time to take a look at this and I think I have found the issues.

- is-directory should run first, set `sort` to `10`
- file-exists strategy should be renamed to no-file-exists
- no-file-exists should run after is-directory so set `sort` to `20`
- fix bug in is-directory, you have `dirExists(dirExists(` when only one should exist.

Once you fix those, you should get some green lights on the tests :)

Cheers!

**Comment by joelnet** [comment]
Finally got around to merging your code into the codebase! Thanks for the PR!

**Pull request merged**
