### PR TITLE
refactor cd.command.js to use strategy pattern

### PR DESCRIPTION
**Pull request by Krayorn**
[https://github.com/joelnet/the-terminal-daemon/issues/18](https://github.com/joelnet/the-terminal-daemon/issues/18)

### CODE REVIEW

**Comment by Krayorn** [comment]
- [ ] add a function to avoid code duplication in `pathExists.strategy.js`
- [ ] find why when using the cd and wallet function with invalid params the name is undefined

**Comment by Krayorn** [comment]
Ok everything seems to work on my end.

i explained the issue i got with the `name` variable in a comment in the code, i hope it's clear enough.

I don't find my fix for the `undefined` when calling `name` in the `invalid.strategy.js` really elegant, maybe we could put the name variable in a `cd.constants.js` file at the same level as `cd.command.js` and then both `invalid.strategy.js` and `cd.command.js` can then import the `name` from that file ?

**Comment by joelnet** [comment]
I see what you are talking about in the comments. What you did was the right way to fix it. In the end I decided it was too complicated just to import `cd`, so I just killed the import completely.

I have merged this into master.

Thanks!

**Comment by Krayorn** [comment]
Ok thanks ! 

Just to let you know, i fixed the wallet command 'undefined' name in my PR as well, so there is still the module.exports.name = 'wallet' in `wallet.command.js`, you may want to do the same little refacto you did in the `cd.command.js` file. 

I may take the issue #20 today or tomorrow :)

**Comment by joelnet** [comment]
I saw your fix. I made some minor refactoring and then merged it into master. Be sure to get latest!

Unit tests will be the next big thing. It's hard to refactor code and know it hasn't broken anything without them. So I think they are going to be important for any of the other strategy pattern refactorings.

Let me know if you have questions.

Would a Discord channel help?

https://discordapp.com/invite/Gg7ptD5

**Pull request merged**
